project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - blog.qmd
    - posts/*/index.qmd
  resources:
    - .nojekyll

website:
  title: "Vaibhav's AI Notebook"
  site-url: "https://vespersword.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true